# Generated by Django 4.1.1 on 2022-10-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rubric_superrubricmanager_subrubric_superrubric_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperRubricManager',
        ),
    ]
